
variables:
  CONTAINER_TEST_IMAGE: mooncloud-repository:4567/root/emptyprobe:$CI_BUILD_REF_NAME
  CONTAINER_RELEASE_IMAGE: mooncloud-repository:4567/root/emptyprobe:latest

stages:
  - build
  - test
  - release

before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN mooncloud-repository:4567
build:
  stage: build
  script:
    - docker build -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE
test:
  stage: test
  script:
    - echo '{}' | docker run -i --rm $CONTAINER_TEST_IMAGE

release:
  stage: release
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
  only:
    - master
